kind: pipeline
type: docker
name: build

clone:
  depth: 1

steps:
- name: cooked
  image: kry9ton/image:latest
  environment:
    token:
      from_secret: bot_api
    github_cert:
      from_secret: github_cert
    SF_PASS:
      from_secret: sf_pass
    DEVICE: miatoll_gcc
    POST_DIR: miatoll
    RELEASE: true
    CODENAME: Alisha
    TYPE: BLC
    CHANGELOG: |
      NOTES!!! A11 enforce only<br>• Rebased kernel source<br>• Merge 4.14.232<br>• Add GCC Graphite Optimisation<br>• Enable BPF JIT<br>• Use GCC instead of Clang<br>• Fix USB OTG<br>• Make scheduling period more efficient<br>• Use Queued Spinlocks<br>• another improvement
  commands:
  - git clone https://github.com/Kry9toN-Project/Drone-CI
  - mv Drone-CI/* .
  - bash main.sh
