kind: pipeline
type: docker
name: build

clone:
  depth: 1

steps:
- name: cooked
  image: kry9ton/image:latest
  environment:
    token:
      from_secret: bot_api
    github_cert:
      from_secret: github_cert
    SF_PASS:
      from_secret: sf_pass
    DEVICE: miatoll_gcc
    POST_DIR: miatoll
    RELEASE: false
    CODENAME: Holmes
    TYPE: BLC
    CHANGELOG: |
      NOTES!!! A11 enforce only<br>• ashmem: Rewrite to improve clarity and performance<br>• drm/kgsl: Reduce latency while processing ioctls<br>• Checkout drivers/char/srandom from positron kernel<br>• Use GCC instead of Clang
  commands:
  - git clone https://github.com/Kry9toN-Project/Drone-CI
  - mv Drone-CI/* .
  - bash main.sh
