kind: pipeline
type: docker
name: build

clone:
  depth: 1

steps:
- name: cooked
  image: kry9ton/image:latest
  environment:
    token:
      from_secret: bot_api
    github_cert:
      from_secret: github_cert
    SF_PASS:
      from_secret: sf_pass
    DEVICE: miatoll_gcc
    POST_DIR: miatoll
    RELEASE: true
    CODENAME: Noona
    TYPE: BLC
    CHANGELOG: |
      NOTES!!! A11 enforce only<br>• Disable PAN emulation<br>• Enable Devfreq Boost<br>• Disable System Trace Module<br>• TLB changes<br>• use SLMK<br>• Switch to qca6174 QCA_CLD profile<br>• Disable qcom memory dump driver<br>• Disable IPC_LOGGING<br>• Remove rcupdate.rcu_expedited
  commands:
  - git clone https://github.com/Kry9toN-Project/Drone-CI
  - mv Drone-CI/* .
  - bash main.sh
